//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Customer : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Outputs = new HashSet<Output>();
        }

        private Nullable<int> _Id;
        private string _DisplayName;
        private Nullable<System.DateTime> _BirthDay;
        private string _Sex;
        private string _Address;
        private string _Phone;
        private string _Email;
        private string _MoreInfo;
        private Nullable<System.DateTime> _ContractDate;
        private string _Status;
        private string _LinkImage;
        private ICollection<Output> _Outputs;


        public Nullable<int> Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> BirthDay { get => _BirthDay; set { _BirthDay = value; OnPropertyChanged(); } }
        public string Sex { get => _Sex; set { _Sex = value; OnPropertyChanged(); } }
        public string Phone { get => _Phone; set { _Phone = value; OnPropertyChanged(); } }
        public string Address { get => _Address; set { _Address = value; OnPropertyChanged(); } }
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }
        public string MoreInfo { get => _MoreInfo; set { _MoreInfo = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> ContractDate { get => _ContractDate; set { _ContractDate = value; OnPropertyChanged(); } }
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }
        public string LinkImage { get => _LinkImage; set { _LinkImage = value; OnPropertyChanged(); } }


        private bool _IsSelected;
        public bool IsSelected { get => _IsSelected; set { _IsSelected = value; OnPropertyChanged(); } }
        private int _IsVisible;
        public int IsVisible { get => _IsVisible; set { _IsVisible = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Output> Outputs { get => _Outputs; set { _Outputs = value; OnPropertyChanged(); } }


    }
}
