//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;

    public partial class InputInfo : BaseViewModel
    {





        private string _IdInput;
        private string _IdObject;
        private Nullable<double> _Price;
        private Nullable<int> _Quantity;
        private Nullable<double> _Discount;
        private Nullable<int> _Stock;
        private Output _Input;
        private Object _Object;



        public string IdInput { get => _IdInput; set { _IdInput = value; OnPropertyChanged(); } }
        public string IdObject { get => _IdObject; set { _IdObject = value; OnPropertyChanged(); } }
        public Nullable<double> Price { get => _Price; set { _Price = value; OnPropertyChanged(); } }
        public Nullable<int> Quantity { get => _Quantity; set { _Quantity = value; OnPropertyChanged(); } }
        public Nullable<double> Discount { get => _Discount; set { _Discount = value; OnPropertyChanged(); } }
        public Nullable<int> Stock { get => _Stock; set { _Stock = value; OnPropertyChanged(); } }

        public virtual Output Input { get => _Input; set { _Input = value; OnPropertyChanged(); } }
        public virtual Object Object { get => _Object; set { _Object = value; OnPropertyChanged(); } }
    }
}
