//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Input : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Input()
        {
            this.InputInfoes = new HashSet<InputInfo>();
        }

        private string _Id;
        private int _IdUser;
        private Nullable<int> _IdSupplier;
        private Nullable<System.DateTime> _DateInput;
        private Nullable<double> _Discount;
        private string _Payment;
        private Nullable<double> _TotalPrice;
        private string _Note;
        private string _Status;

        private int _TotalObject;

        private int _TotalQuantity;

        private Supplier _Supplier;
        private User _User;

        private ICollection<InputInfo> _InputInfoes;



        public string Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public int IdUser { get => _IdUser; set { _IdUser = value; OnPropertyChanged(); } }
        public Nullable<int> IdSupplier { get => _IdSupplier; set { _IdSupplier = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> DateInput { get => _DateInput; set { _DateInput = value; OnPropertyChanged(); } }
        public Nullable<double> Discount { get => _Discount; set { _Discount = value; OnPropertyChanged(); } }
        public string Payment { get => _Payment; set { _Payment = value; OnPropertyChanged(); } }
        public Nullable<double> TotalPrice { get => _TotalPrice; set { _TotalPrice = value; OnPropertyChanged(); } }
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }

        public int TotalObject { get => _TotalObject; set { _TotalObject = value; OnPropertyChanged(); } }

        public int TotalQuantity { get => _TotalQuantity; set { _TotalQuantity = value; OnPropertyChanged(); } }

        public virtual Supplier Supplier { get => _Supplier; set { _Supplier = value; OnPropertyChanged(); } }
        public virtual User User { get => _User; set { _User = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get => _InputInfoes; set { _InputInfoes = value; OnPropertyChanged(); } }
    }
}
