//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Object : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.InputInfoes = new HashSet<OutputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }
        private string _Id;
        public string Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }

        private string _DisplayName;
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }

        private Nullable<int> _IdUnit;
        public Nullable<int> IdUnit { get => _IdUnit; set { _IdUnit = value; OnPropertyChanged(); } }

        private int _IdCategory;
        public int IdCategory { get => _IdCategory; set { _IdCategory = value; OnPropertyChanged(); } }

        private Nullable<double> _InputPrice;
        public Nullable<double> InputPrice { get => _InputPrice; set { _InputPrice = value; OnPropertyChanged(); } }

        private Nullable<double> _OutputPrice;
        public Nullable<double> OutputPrice { get => _OutputPrice; set { _OutputPrice = value; OnPropertyChanged(); } }

        private Nullable<int> _Count;
        public Nullable<int> Count { get => _Count; set { _Count = value; OnPropertyChanged(); } }

        private Nullable<int> _IdPosition;
        public Nullable<int> IdPosition { get => _IdPosition; set { _IdPosition = value; OnPropertyChanged(); } }

        private string _LinkImage;
        public string LinkImage { get => _LinkImage; set { _LinkImage = value; OnPropertyChanged(); } }

        private string _Status;
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }

        private bool _IsSelected;
        public bool IsSelected { get => _IsSelected; set { _IsSelected = value; OnPropertyChanged(); } }
        private int _IsVisible;
        public int IsVisible { get => _IsVisible; set { _IsVisible = value; OnPropertyChanged(); } }

        private Category _Category;
        public virtual Category Category { get => _Category; set { _Category = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        private ICollection<OutputInfo> _InputInfoes;
        public virtual ICollection<OutputInfo> InputInfoes { get => _InputInfoes; set { _InputInfoes = value; OnPropertyChanged(); } }

        private Position _Position;
        public virtual Position Position { get => _Position; set { _Position = value; OnPropertyChanged(); } }

        private Unit _Unit;
        public virtual Unit Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        private ICollection<OutputInfo> _OutputInfoes;
        public virtual ICollection<OutputInfo> OutputInfoes { get => _OutputInfoes; set { _OutputInfoes = value; OnPropertyChanged(); } }
    }
}
