//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using QuanLyKho.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class Output : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Output()
        {
            this.OutputInfoes = new HashSet<OutputInfo>();
        }

        private string _Id;
        private int _IdUser;
        private Nullable<int> _IdCustomer;
        private Nullable<System.DateTime> _DateOutput;
        private Nullable<double> _Discount;
        private string _Payment;
        private Nullable<double> _TotalPrice;
        private string _Note;
        private string _Status;
        private Customer _Customer;
        private User _User;
        private ICollection<OutputInfo> _OutputInfoes;



        public string Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public int IdUser { get => _IdUser; set { _IdUser = value; OnPropertyChanged(); } }
        public Nullable<int> IdCustomer { get => _IdCustomer; set { _IdCustomer = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> DateOutput { get => _DateOutput; set { _DateOutput = value; OnPropertyChanged(); } }
        public Nullable<double> Discount { get => _Discount; set { _Discount = value; OnPropertyChanged(); } }
        public string Payment { get => _Payment; set { _Payment = value; OnPropertyChanged(); } }
        public Nullable<double> TotalPrice { get => _TotalPrice; set { _TotalPrice = value; OnPropertyChanged(); } }
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }

        public virtual Customer Customer { get => _Customer; set { _Customer = value; OnPropertyChanged(); } }
        public virtual User User { get => _User; set { _User = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get => _OutputInfoes; set { _OutputInfoes = value; OnPropertyChanged(); } }

    }
}
